const list = [
    {
      id: 1,
      title: "Chicken briyani",
      price: 89,
      img: "./images/x1.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Sandwich",
      price: 98,
      img: "./images/x2.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Chicken rice ",
      price: 143,
      img: "./images/ff1.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Blackcurrent shake",
      price: 57,
      img: "./images/s5.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Dragon chicken",
      price: 149,
      img: "./images/x3.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Chocolate shake",
      price: 135,
      img: "./images/s11.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Veg noodles ",
      price: 693,
      img: "./images/s3.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Dosa",
      price: 289,
      img: "./images/s10.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Chilli chicken ",
      price: 80,
      img: "./images/x4.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Idly",
      price: 86,
      img: "./images/s7.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "French fries",
      price: 120,
      img: "./images/x5.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Brownie",
      price: 157,
      img: "./images/x6.jpg",
      amount: 1,
    },
];
export default list;